### ISSUE TITLE
Story/Achievement Traits

### ISSUE THREAD

**Issue by thefinestsieve** [EMFTeam/EMF#194]
These would be traits handed out for any character who manages to achieve something rare or usual.

Here's the beginning of a list from initial suggestions by @zijistark:
* Dynasty Breaker: for unseating a Karling, Seljuk, or Doukas on a king- or higher-tier title)
* Destroyer of Empires: for causing an empire to collapse?
* Original Emperor: first of your dynasty to found an empire
* Holy Smoke: sacrificed a head of religion

**Comment by zijistark** [comment]
Sacker of Cities?
  -- Character has successfully sieged or assaulted 25-30+ settlements.  [Could be made probabilistic to avoid keeping a variable around for everybody that's ever led a siege.]

**Comment by zijistark** [comment]
Executioner
-- Character has executed more than 20 characters.

(Could tie into that kill count feature and/or ambition for the cruel)

**Comment by thefinestsieve** [comment]
* Lifer: adults who have spent vast majority of life in prison
* From Humble Beginnings: lowborn who became duke (king?) or higher tier
