### ISSUE TITLE
Better CB cooldowns

### ISSUE THREAD

**Issue by zijistark** [EMFTeam/EMF#224]
CB cooldowns should not be added in the ````on_add```` section of CBs but in the ````on_fail````, ````on_success````, and ````on_reverse_demand````.  They should also be shortened to account for the fact that they'd then no longer include the time to complete the war (3 or 4 years for the currently-5).  The ````on_add```` should still have a custom tooltip explaining that a cooldown will be added when the war ends (if they're enabled, as default).

This is a more plausible time to add a cooldown (as arbitrary as it still is), and it doesn't add cooldowns when the war invalidates.

**Comment by thefinestsieve** [comment]
I remember suggesting this ages ago, or maybe someone else did, but it definitely came up. Anyway, if I remember correctly, the discussion at the time brought up the suggestion that we could measure the time the war takes (roughly) and then choose a smaller cooldown based on that.

**Comment by zijistark** [comment]
Measuring the time that the war takes seems pretty complex to me.  TOMs don't support querying the time since they've been set either, so we'd just have to set a character flag on the attacker ````on_add````, but this would get confused by simultaneous wars.  Then you've got the issue of actually applying different grades of cooldown dependent upon how long that flag's been set, which seems like a lot of complexity with little gain compared to just, e.g., shrinking the after-war-is-over cooldown to 3 years for CBs with such timed cooldowns (as opposed to CBs with lifetime cooldowns).

Worst case, the war was a really easy win and took less than 2 years: it probably didn't warrant a 5-year cooldown then anyhow, given the plausibility argument for cooldowns.  Most of the time, it will be approx. correct for player wars.

One hole, though: we also have to stop the attacker from engaging in several wars of that type at once (i.e., starting them before completing the first war of that type).

**Comment by zijistark** [comment]
Or, 4 years. Either way.

**Comment by thefinestsieve** [comment]
Limiting folks to a single war of the given type doesn't seem like too much of an issue. That is how it already works. But that also means measuring the time of the war should be easy. If we have to flag everyone who gets into a holy war (so they can't start another) we could easily check for the length of the war at the end. It wouldn't need to be fine-grained, either. Just check for lengths of 1, 2, 3, and 4 years and set the cooldown timer appropriately.

**Comment by zijistark** [comment]
I was hoping to avoid character flags... (needs cleanup by a maintenance event), but I suppose that a modifier wouldn't be a very effective workaround for their need anyway.

**Comment by thefinestsieve** [comment]
Is it even possible to avoid having cleanup? That lack of on_invalidation in CBs (and in war related on_actions, for that matter) seems like it would make it necessary no matter what. If we wanted, we might be able to add a tidbit to all the CBs governed by that initial flag so that if you've had it for over a certain amount of time you can go to war anyway (and then it clears it off and resets it)

**Comment by zijistark** [comment]
Yeah, it's not possible to avoid cleanup (assuming you prevent spamming multiple wars of the same type at the same time) unless you use timed character modifiers to block the multi-war stuff.
