### ISSUE TITLE
Better HRE Creation

### ISSUE THREAD

**Issue by zijistark** [EMFTeam/EMF#256]
WAS: **Fix HRE formation conditions**

That is to say, completely throw away the vanilla-based junk that EMF adopted with the Charlemagne patch (with adaptations to make it SWMH-friendly).  I've always known that it was in a suboptimal state since CM, but I realized today that it's even arguably broken on EMF+SWMH (that is, essentially nobody but a Karling can form it in the 867 start on SWMH except under rare circumstances due to the titular nature of `k_germany` and a few other things on that map).

I'm actually rather embarrassed that it's been in this state since as long as CM. And apparently our SWMH users do indeed avoid playing under the Karlings in the 867 start, or somebody would've complained about how ridiculous the situation is. Point of shame taken.

The vanilla decision needs to be completely thrown-out. I suppose that the vanilla-based `form_the_hre_early` can stay for now (a 769-only version of the decision, so it doesn't apply to SWMH), but ideally, the new set of decisions for HRE formation should probably work with either early start.

It should be interesting and rewarding to form the HRE, and it should be possible-- in some incarnation-- for any European Catholic to form a plausible version of the HRE.  At minimum, we should fall back to the main options we had before CM: *Form the French HRE*, and *Form the HRE* (German / standard).

However, it's not as easy as just reverting to the old PB stuff:

- Our creation conditions pre-CM relied upon a modified vanilla landed_titles structure that mirrored SWMH better in the region.  Since CM, EMF has used a landed_titles structure that is deliberately very close to vanilla, and that shouldn't change in any [major] way.  The SWMH and vanilla involved titles and actual de jure territory are very different.

Plus:

- Creation of the HRE should be more robust, resulting in fewer border messes for the fledgling HRE.  Some of this may mean altering the types of titles available to the initial kings in 867 or modifiers on faction weights on EMF+SWMH, as currently their titular setup tends to lead to massive internal strife and independence, before forming, unnecessarily.

- We should ideally also toss-out vanilla's 769 HRE formation decision, so we should have an eye on supporting formation from 769 too.  Formation from 769 should allow for much more flexibility in what the HRE looks like.

- Any ideas on improving HRE formation and general unification challenge/achievement while at the same time making it easier for the AI to achieve a historical HRE within a century or so of the 867 start date (and not super fast, either-- I'd like to see non-Karling AIs forming it occasionally) are very welcome.

**Comment by zijistark** [comment]
For starters, I'd like to alter the SWMH de jure setup for the HRE in the 867 start.  Lotharingia and Germany shouldn't be titular.

- `k_lotharingia` shall replace the titles `k_upper_lorraine` and `k_lower_lorraine`
- `k_germany` shall replace the titles `k_franconia` and `k_saxony`

Upon formation of the HRE, the traditional SWMH de jure titles shall be swapped back into place. `k_germany` and `k_lotharingia` will again be titular.

This makes it easier to use a unified decision for the two maps, but more importantly, stops lots of Karling vassals from rebelling + border gore, and it also improves how the AI thinks about these no-longer-titular titles as well as gives proper de jure claims on those who do revolt.

**Comment by zijistark** [comment]
Seems like the simplest thing to do further is remodel the decision into two: one for forming the HRE (standard) and one for forming the french HRE (different de jure territory, white-blue colors, possibility of native localisation, harder).  PB already sort of does this (though vanilla map de jure structure is different now), and that's basically what I'll rewrite, unless somebody has any more grand ideas regarding HRE formation.

**Comment by escalonn** [comment]
thought: this is hampered by the bad CK2 Catholic/Orthodox abstraction, but the possibility for a closer ERE-Pope relationship, which hinders or even prevents HRE formation, culminating in a mend-schism-early event of some kind and possibly an expansion of the ERE de jure territory over, say, Italia, and opening up some imperial reconquest in the west (if the de jure change doesn't achieve that; i forget how EMF does rome)

**Comment by zijistark** [comment]
@escalonn For 867 starts? I think the Pope was squarely not in favor of submitting to the ERE again at that point. Charlemagne rather ruined that possibility for the ERE, although I agree that an expansion of the 769 start's ERE-papal options would be a plus. In 867, it would take some seriously-good Papal relations (e.g., if it were possible for Orthodox bishops to become Cardinals in some half-mended state...) for the Roman Catholic church to un-mend the schism and recognize the ERE as protector of the Papacy/Catholicism.  Perhaps if the Pope could be subjugated by the ERE? [A special CB very similar to the force-vassalization one added recently could be given after `completely_controls = k_sicily` so long as there's still no HRE, but various Catholic rulers might join against the ERE depending on zeal.]

Regarding a de jure change handing `e_italy` to the ERE, yes, that would open-up Imperial Reconquest over there on tier 1.

Progress so far (committing soonish):

- SWMH de jure stem duchy `k_schwaben` also gets absorbed by `k_germany` for 867 starts, to be automagically restored when/if the HRE is formed.  They could honestly go to `k_bavaria` instead, but I figure `k_bavaria` should remain a relatively rump kingdom like `k_bohemia`.  Basically, no HRE stem duchies in 867-- only the Karling titles, the always-silly `k_frisia`, and ever-noble `k_bohemia`.

- New decision for the standard HRE's formation (not the French HRE, a bonus feature) with map-specific behavior segregated into a compatch-overridden `events/emf_hre_map.txt` (not unlike there's now an `events/emf_startup_map.txt` for the separate dynamic de jure setup for vanilla/SWMH). *[Decision untested at time of writing]*
  - Currently relying on the Crier module for an empire creation announcement / flavor.

Once that's done and all tested, we should have something to ship Friday, and I can take the "bug" label off this Issue.

The French HRE can be added with a little more time; it doesn't complicate things much.  It just needs a flag/color/title and probably a decision to rename the empire *Saint-Empire Romain* in the spirit of one of the neat cases of native localisation. It also does leave the question of whether to make all of the already-de-jure-on-SWMH `e_hre` part of `e_emf_hre_french` (in addition to `e_france`) or whether to take the parts that would've belonged to `e_germany` on vanilla and indeed assign them to that title.  I'd make the French HRE a first-line feature, but apparently our players don't really put a big value on HRE stuff, so I'm in no hurry.

**Comment by zijistark** [comment]
Doh, it occurs to me that there's also the spectacular, de jure 1-duchy `k_carinthia` stem duchy on SWMH. [No wonder this stuff falls apart in 867 so spectacularly.] I may also merge this one into `k_bavaria` in the 867 start, then break it back out again upon HRE formation.

I didn't want to run roughshod over SWMH's HRE setup in 867, but it appears that I have anyway. Hopefully none of this stuff has changed in the SWMH EE beta either.

**Comment by zijistark** [comment]
Update: The code's now committed that should cover the classic 867 case of forming the HRE very well (with particular attention paid to altering SWMH's title setup dynamically to be more amenable to decent outcomes without losing its stem duchy setup).

For the Future:

- *Form the Saint-Empire Romain*, an alternate formation decision (mostly for player achievements but certainly possible for the AI once in a blue moon) that is French-centric and results in an `e_hre` (though it will not be called that) with a properly light-blue French color and de jure territory of, essentially in vanilla terms, `e_france` (which also includes `k_frisia` at its northernmost tip) and `k_lotharingia` with the rest of the classic HRE turned into an ahistorical `e_germany` (unless NAE is enabled-- no de jure empire then, of course)-- without any stem duchy titles. The *Saint Empire-Romain* will probably not be forced to Agnatic Elective succession.

- [Different topic, if I don't just solve it first.] Papal coronation for the *King of the Romans* title, which will be a constantly ongoing mechanic in a campaign but also of course be relevant for the Empire's formation.

**Comment by escalonn** [comment]
> an expansion of the 769 start's ERE-papal options

Which options are those? Is this something HIP or vanilla?

> Papal coronation for the *King of the Romans* title

Isn’t it rather the other way around? The electors elected you king, you were crowned at Aachen as *rex romanorum* (a.k.a. *teutonicorum*) (and maybe again as *rex italiae* in Lombardy) but only the Pope could crown you *imperator romanorum*.

**Comment by zijistark** [comment]
@escalonn 

> Which options are those? Is this something HIP or vanilla?

None currently, so vanilla.

> Isn’t it rather the other way around? The electors elected you king, you were crowned at Aachen as rex romanorum (a.k.a. teutonicorum) (and maybe again as rex italiae in Lombardy) but only the Pope could crown you imperator romanorum.

Well, we sort of have to do it backwards admittedly, and I suppose that I may not have stated that correctly, which is partly a product of my lack of knowledge upon the subject.  Being the Emperor of the HRE implies being effectively elected *King of the Romans* already (though it *is* possible to take the title by force of claimant faction, abdication, claim, or other means, which in a perfect world would also get special treatment), at least once it is formed already.

The Papal coronation would indeed be for the imperial title.  This 'title' is just going to have to be represented as a trait in-game (or could be a specially-managed titular title too, just to be neat, as long as it was listed in the character tooltip right under Emperor of Holy Roman Empire (or Emperor of Spain, or whatever) as *Imperator Romanorum*.  A Catholic Emperor will have to request a Papal coronation, which may be denied, delayed, or accepted.  AI HREs will try to request a Papal coronation as soon as they can.  As long as there is no other living Catholic emperor that hasn't been denied and relations are acceptable, the request will be either accepted or delayed.

The first Papal coronation (post-CM) should be a major narrative event. Following Papal coronations will still all be major events for Christian emperors or their kin (nobody else really cares to see that many oaths sworn) [note: "major" event means broadcast, in the longer `narrative_event` form].  Probably a major event as well for all Catholics if the Pope switches his coronation choice to a new empire (e.g., a goody-goody player empire with Papal Investiture that's become powerful and has a relatively Charlemagne-like ruler, or Papal relations with the HRE are just terrible).

**Comment by escalonn** [comment]
@zijistark I mean, what are those vanilla ERE-papal options? Don't know what that would be. Here are some things that would be good.

* the King of the Romans is *not* called Kaiser/Emperor while he is uncrowned by the Pope
* you can't be crowned during a regency or while at war (IIRC emperors-elect who were too busy in Germany wouldn't be crowned for years)

And what do you think of this:

* the Holy Roman Empire title is *not* held by an uncrowned King of the Romans
  * this would require a second empire-level king of the romans title, presumably titular (though... given that only Germany is de jure HRE, at least in the current setup, you could even make the HRE titular instead)

I like your idea of the Pope crowning someone else as Emperor of the Romans in the right circumstances. I had a game where I took Sicily to a custom empire that held all of Africa as well, and I could see if the HRE fractured or fell into heresy, the Pope would think about doing that. If the Emperor of the Romans coronation is just the HRE title, like I suggested above, then this would probably mean de jure changes. The former HRE would instantly shift under the King of the Romans de jure, and maybe some of its vassals would just declare independence. Stuff controlled by the new HRE would instantly drift in.

Or is it even possible for the HRE title to work this way, if succession's not moddable? Ideally the title would just be destroyed every time the ruler died.

In cases of huge power imbalance in favor of the Emperor, maybe just if he vassalizes the Pope and is impious, he can skip the coronation business and the emperors-elect will always just become emperor. Dunno.

**Comment by zijistark** [comment]
@escalonn 

I've considered making a second title for the HRE that is actually the "[frankish/german] king of the romans" real de jure title and making the HRE itself titular, although this is admittedly pretty dramatic.  One silly bit is that the real empire title might have to localise to "Romans" (w/ `short_name = yes` in the title definition) to achieve the desired title schema.

How it'd work:

Feudal Elective would properly elect the traditional King of the Romans (a de jure empire title that we'll call `e_german_hre` for the moment) without anything to do with the Pope (and would continue to do so even if the Pope told the Franks/Germans to shove it and sided with some grand Jimena empire as the official [catholic] empire of the Romans a few hundred years later).

In this case, we couldn't call him an Emperor-Elect due to CK2 inflexibility, but he could certainly just be "King [of the Romans]" only until/if a Papal coronation granted him the Holy Roman Emperor title (after which he'd be both), which would have `dignity = 1000` or something (count as 1000 provinces in terms of determining which titles are primary, so he'd switch it to be his primary title and keep it that way, while ideally maintaining the `e_german_hre` de jure title as secondary).  Upon death of whoever holds the HRE title, the title would be destroyed until the next coronation (if ever).

This would lend well to passing the baton to other empires too.  They'd just literally receive the `e_hre` titular mega-title instead of those German guys.

Sidenote: I'd rather not try to try model the transition to the period when coronations ended (all emperor-elects thereafter), because CK2 is just really bad about being flexible with titles and this would complicate things even more, since yet another de jure empire title would somehow have to be swapped-in just to change the `title` property of the title's definition.

NOW... what to do if the Schism is mended, folks?  [Either the traditional one, or Catholicism prevails over Orthodoxy.]  Suddenly the ERE/RE starts to encroach on this idea of an HRE.  If the Catholics mend the Schism, it's simpler: the ERE just becomes another empire capable of being also titled Holy Roman Emperor (presuming he's Catholic).  If it happens the other way, well, it starts to get ugly.  There's no more Papal coronations, period, if there cease to exist any non-Orthodox empires.

**Comment by zijistark** [comment]
One major "problem" with the above suggestion is that, if another AI empire became the titular HRE through coronation, it would adopt the colors/flag of the HRE wherever they were rather than keep their original flag/colors.  [Likewise, `e_german_hre` (King of the Romans) would need same colors and flag as `e_hre`, or else the map would be all over the place between coronations.]

For the player, this doesn't matter, because they would have to manually make 'Holy Roman Emperor' their primary title and have no need to do so.  I can, however, see the Catholic Schism getting mended and a Byzantium called "Holy Roman Empire" with HRE colors happening from this setup.

**Comment by zijistark** [comment]
Oh, another problem:

If players DID make 'Holy Roman Empire' their primary title after being coronated, then the uncoronated `e_german_hre` and they are sharing the same flag/colors.

FURTHERMORE, one cannot set a different map display name and title display name for a title, so between coronations even in the simple case, we'd have a big, fat "Romans" sitting on the map until coronation.  If you try to override the name via event or something, you're going to override it for the title display of the actual King of the Romans too, who will become "King of the Holy Roman Empire."

[And none of that sits well with native localisation, either.]

**Comment by escalonn** [comment]
You could call it the "Kingdom of the Romans" (with short_name = yes), with ruler title "King of the Romans", couldn't you?

If Catholic wins, a Catholic Byzantine Empire could just become the HRE as you say. IMO simply mending the schism doesn't necessarily mean the Pope would favor the Greek claim to the empire. But on the other hand, there was the Latin Empire. I don't really know what the "de jure map" in the mind of the West was with that. Was the HRE offended? I am pretty curious and will have to research that some time.

Yeah, CoA is an issue, with somebody besides the Germans getting coronated, though I think I could live with a Jimena or a Komnenos HRE having the double eagle. (oddly, the first two dynasties I thought of... already have black eagles on yellow ground...) (I don't see how it matters if players make HRE their primary title.) Don't see a problem for native localisation, though.

**Comment by zijistark** [comment]
That naming scheme would result in "King of the Romans of Kingdom of the Romans."

**Comment by escalonn** [comment]
:(

Well, maybe you could handwave a little and replace "King of the Romans" with "King of the Germans" in all this. "Germans" looks alright on the map.

**Comment by zijistark** [comment]
I don't think that I'm willing to see the HRE fluttering around between "Germans" and "Holy Roman Empire."

Also, again, it'd be problematic if the HRE were made primary by an AI empire (like the ERE) since they'd then match map colors (and flag, as mentioned, although technically we could probably do something about that through dynamic CoA control) with the "Germans" blob up there.

I suppose that there's always the possibility of creating a dynamic titular title for the HRE which uses whichever other empire title as its `base_title` so that colors are based upon it and CoA is the same.  Still, I don't think this can solve the "Germans" problem, and it wouldn't be able to be `short_name = yes` due to `create_title` limitations (I think-- I have done some interesting localisations for temp. titles before, so maybe not).

**Comment by zijistark** [comment]
Update: This has turned into an extended project.

I've now created a Holy Roman Unification CB (tentative name) which assists with more plausible, reliable, stable, and interesting formation of the HRE under the pretext of restoration of the Carolingien Empire.  It is essentially a very custom claim CB that allows for more reasonable paths to formation but also works alongside existing claim CBs (as actually having an inherited claim is not always required to use it, and it is paced with a cooldown).

I've gone through a real campaign attempting to form the HRE on EMF+SWMH as the [custom] Duke of Rheinfranken (Franconia in vanilla) as fast as I possibly can.  This has helped guide the CB's design and will continue to do so (still haven't formed it in my game) but has also spawned a variety of other topics for improvement as I encounter roadblocks, notice issues, and generally Play. [This was actually designed to be a game to get a feel for what it's like playing a Catholic locked in Gavelkind and dealing with the new Crown Authority system originally, so there's a lot to take-in.]

The CB should be in the next release, although I anticipate that it will require a fair bit more tweaking along with results from observes before it's ready.

**Comment by hfarm** [comment]
I was thinking about this HRE situation a long time ago (had some suggestions in the HIP forum but in the end real life and lack of experience meant my coding never got far). I ended up with a similar idea to yours so it's great to see that you're going to be putting this into practice. 

In terms of the CB. Does k_italy currently join the HRE dejure?  I was thinking that whoever forms the HRE italy should remain outside the deJure empire but instead the HRE should have a HRE reconquest CB. Intuitively it seemed like this would lead to a nice dynamic in which k_italy is destroyed on HRE formation and then the non-dejure italian vassals went into a cycle of breaking off and being reconquered by the Emperor much like in real history. It also had the bonus of stopping the italians being able to vote on who should be emperor. Perhaps access to the CB could be linked to holding the crowned trait to show you had a legitimate claim on the lands of italy.

Another idea I had was adding a path for a king of italy to become HRE by holding Italy, Sicily and maybe also a couple of other kingdoms (or just having the correct realm size). This version of the empire should also transfer all the de jure papal terrotory bar latium to k_italy (representing the emperors subordination of the pope as a temporal power) and maybe add burgundy and carinthia to the dejure italian_hre?

Possibly it might also make sense to have a path straight from Lotharingia to the HRE if they can hold Italy. In that case I would guess you would need a core of Lotharingia, Burgunday and Frisia as the dejure HRE perhaps with the added bonus of gaining weak claims on both France and Germany. However this may be unnescessary. 

It might also be good to add a customisation that removes the dejure HRE from the SWMH 867 start and replaces it with e_germania as I feel like at that point there's little historical justification for the German HRE being dejure rather than the French (or Italian)

**Comment by zijistark** [comment]
Worth noting that there's now a `set_special_character_title = KEY` (e.g., a vanilla usage is with KEY=GENGHIS_KHAN).  It is possible that this could be used for the 'King of the Romans' pseudo-title.
