### ISSUE TITLE
New demense law slider: Bureaucracy

### ISSUE THREAD

**Issue by zijistark** [EMFTeam/EMF#26]
Kind of like the crown levies slider but for taxes, but with some twists:

*Bureaucracy:*

Slider settings:

- ***None*** Default.  No effects.
- ***Minimal*** Gives +1 demesne size. Negative vassal opinion. Requires tier at least duke.
- ***Sophisticated*** Gives +2 demesne size.  Gives +7.5% blanket vassal tax law modifiers.  Significant negative vassal opinion.  Feudal vassal opinion hit is higher than theocracies which is higher than republics (due to relative, mutual benefits from improved efficiency of bureaucratic structure-- the 3 government types each adapt to more sophistication with varied degrees of efficiency).  Requires tier at least king (or great duke w/ realm_size >= 30) and TECH_LEGALISM at least 4 anywhere in the direct demesne of the ruler.
- ***Maximum*** Gives +3 demesne size.  Gives +15% blanket vassal tax law modifiers.  Major vassal opinion hit. Same relative malus ratio for the 3 vassal classes as prior setting (should be quite high, as laws go, for feudal vassals, though not *all* that different).  Requires at least king tier.  Requires TECH_LEGALISM at least 6 anywhere within the ruler's direct demesne.  This should put this setting into play somewhere around, oh, 1200-1250?

**Comment by thefinestsieve** [comment]
Considering this was effectively added to the vanilla game, this should probably be closed.
