### ISSUE TITLE
Remaining 2.4 compatch considerations (working issue)

### ISSUE THREAD

**Issue by zijistark** [EMFTeam/EMF#283]
To keep track of things that still need to be done for the 2.4 compatch or looked at in the immediate future thereafter, I've created this issue.

- [x] Job actions
- [x] Adapt localisation from `feudal_slider` and `feudal_obligations` law groups to new `tribal_slider` and `tribal_obligations` (currently has nothing)
- [x] Finish compatching `realm_decisions.txt`
- [x] Fix parse error in `minor_decisions.txt` (error starts around line 274)
- [ ] Re-import all vanilla character history files that have `spawn_unit` effects in them and earmark all the unmarked units with `start_troops` (after updating `emf_nwo`)
- [x] Replace all usages of `continent = region_sahara` with a real geographical region (currently has been removed from some places and replaced with a "FIXME" comment, remains in others)
- [x] Finish removing all old savegame-compatibility measures from the EMF 3 cycle
- [x] Determine why debug output is claiming that the traits `in_hiding`, `incapable`, `kshatriya`, `brahmin`, and the four theological educations are invalid
- [x] Can apparently no longer set/clear global flags directly in history, so alter Isis's historical setup to set the right flags upon startup as part of her big `effect`
- [x] Ensure that the startup routine which seizes minor baronies from randomly-generated barons still works as intended with new government and holding types
- [x] Import everything from PB that still matters into this repository. Use `file2mod_map.txt` to see which files are actually relevant.
- [x] Compatch retinues
- [x] Remove duplicate laws from `decisions/` coming from PB, preferably by ending the installer dependency upon PB files entirely (!)
- [ ] `emf_nwo` (Does not consider nomads, promotes minor province barons to counts via old-style government change, general code review for more loosened constraints on titles, tiers, and provinces in 2.4)
- [x] `emf_mr` (Similar, also definitely doesn't work at changing government form, also badly needs scripted triggers)
- [x] `emf_feudalizer` (Similar, general code review and upgrade)
- [X] Cut EMF's installer dependency upon PB, internally release a new HIP build for EMF+NBRT
- [x] Validate EMF w/o those few remaining files that were from PB gone now
- [x] Folderize EMF on_actions
- [x] Folderize EMF+VEvents on_actions
- [x] Folderize EMF defines.lua overrides
- [x] Remove usage of scripted triggers for councillor requirements from councillor ambitions until/if a fix for the traits issue comes down the pipe
- [x] Add geographical_region for the Sahara on vanilla
- [x] Add geographical_region for the Sahara on SWMH
- [x] Use `emf_region_sahara` checks in all the spots from which the old checks were removed (Ctrl+F sahara-- or just FIXME, I think, as well as the `action_fabricate_claims` province trigger)
- [x] New World Order
  - [x] Do not automatically unland all [remaining, after dealing with Papacy] landless title holders in the case of nomadic holders
  - [x] Add 2 options to setup: Make all clan leaders independent, or leave nomads alone
  - [x] Destroy all tributary relationships
  - [x] Observe whether hordes eat everything else even when clan leaders go independent when using 'independent counts' mode (if so, consider generating nomad capitals for every empty province as an option)

**Comment by thefinestsieve** [comment]
I'll be doing job actions and checking out the minor decisions issue today, for sure.

**Comment by thefinestsieve** [comment]
The debug output issue with the traits is strange. As far as I'm aware, those are all pure vanilla in our version. Have you checked to see if vanilla gets the same errors?

**Comment by zijistark** [comment]
No, I haven't checked against the vanilla error.log

- [ ] Get a baseline debug dump from vanilla for comparison to ours

**Comment by zijistark** [comment]
- [ ] Patch `PB_culture.txt` (`culture_conversion_events.txt`)

**Comment by zijistark** [comment]
It appears that the councillor ambitions are still showing for top lieges. Scripted trigger problem?

**Comment by zijistark** [comment]
- [ ] Import everything from PB that still matters into this repository. Use `file2mod_map.txt` to see which files are actually relevant.
- [ ] Compatch retinues
- [ ] Remove duplicate laws from `decisions/` coming from PB, preferably by ending the installer dependency upon PB files entirely (!)
- [ ] `emf_nwo` (Does not consider nomads, promotes minor province barons to counts via old-style government change, general code review for more loosened constraints on titles, tiers, and provinces in 2.4)
- [ ] `emf_mr` (Similar, also definitely doesn't work at changing government form, also badly needs scripted triggers)
- [ ] `emf_feudalizer` (Similar, general code review and upgrade)

**Comment by thefinestsieve** [comment]
>It appears that the councillor ambitions are still showing for top lieges. Scripted trigger problem?

Are they all showing up or just steward? Because I found a single missing ``independent = no`` in the steward ambition. (Already fixed it.)

**Comment by zijistark** [comment]
Steward only. Cool-coolcoolcool.

**Comment by zijistark** [comment]
- [ ] Design and carry-out a series of tests regarding the scripting interface's notions of province ownership, county ownership, and province capitals (or lack thereof) in the face of the various, new possibilities in a nomadic realm.
- [ ] `emf_autolander` (At min, proper support for nomadic autolanding-- not exactly sure how that should work yet, and revise code to support new constraints on province mechanics as well as `best_fit_character_for_title` filtering that depends upon government form)

**Comment by zijistark** [comment]
- [ ] Fix PB legacy map leakage into EMF due to installer dependency

**Comment by zijistark** [comment]
I took a big swipe at force-importing (force-converting?) most PB files that are still used and stopped the improper leakage of almost as many with placeholders or vanilla imports. I'm very glad for the existence of `file2mod_map.txt`.

@thefinestsieve Maybe you could look over what I imported / blocked as well as the few remaining items from ProjectBalance in a plain EMF install?  We should have all the relevant graphics covered, but it's the text that should be evaluated.

**Comment by zijistark** [comment]
- [ ] Patch everything for the 2.4.2 open beta

**Comment by zijistark** [comment]
- [ ] When this is all done, patch SWMH's `mongol_events.txt` for them

**Comment by zijistark** [comment]
- [ X ] Cut EMF's installer dependency upon PB, internally release a new HIP build for EMF+NBRT
- [ ] Validate EMF w/o those few remaining files that were from PB gone now

**Comment by zijistark** [comment]
- [ ] Address regular retinues still being available to hordes:
  https://forum.paradoxplaza.com/forum/index.php?threads/bug-reports.749756/page-126#post-19666717

**Comment by zijistark** [comment]
- [ ] Folderize EMF on_actions
- [ ] Folderize EMF+VEvents on_actions
- [ ] Folderize EMF defines.lua overrides
- [ ] Remove usage of scripted triggers for councillor requirements from councillor ambitions until/if a fix for the traits issue comes down the pipe
- [ ] Add geographical_region for the Sahara on vanilla
- [ ] Add geographical_region for the Sahara on SWMH
- [ ] Use `emf_region_sahara` checks in all the spots from which the old checks were removed (Ctrl+F sahara-- or just FIXME, I think, as well as the `action_fabricate_claims` province trigger)
- [ ] (New World Order)
  - [ ] Do not automatically unland all [remaining, after dealing with Papacy] landless title holders in the case of nomadic holders
  - [ ] Add 2 options to setup: Make all clan leaders independent, or leave nomads alone
  - [ ] Destroy all tributary relationships
  - [ ] Observe whether hordes eat everything else even when clan leaders go independent when using 'independent counts' mode (if so, consider generating nomad capitals for every empty province as an option)

**Comment by escalonn** [comment]
>Can apparently no longer set/clear global flags directly in history, so alter Isis's historical setup to set the right flags upon startup as part of her big effect

You still can in *title* history, FWIW. Vanilla does that all over the place (And presumably it's not broken...)

**Comment by zijistark** [comment]
Yeah, I guess this was just yet another false positive from `error.log`. That'd really not be so deplorable if it weren't sporting tons of negatives too. [At least Gars said that in 2.5, the greatest source of false positives-- the asserts thrown whenever any perfectly valid variable operation with a negative number or `set_variable` to zero-- will stop flooding the log finally.]
