### ISSUE TITLE
Scenario customization decision: De Jure Shuffle

### ISSUE THREAD

**Issue by zijistark** [EMFTeam/EMF#62]
... which randomly alters the de jure borders of every kingdom on the map, by taking duchies from neighbor kingdoms with preference given from smallest to largest kingdoms.

Could also alter de jure empire borders, though I'm less interested in that.  Would be pretty rad in combination with an equivalent of Shattered Balance Plus that will quickly lead to the establishment of an alternate, somewhat-random-somewhat-recognizable scenario.

**Comment by escalonn** [comment]
Still waiting for 2.4 stuff for this one?

**Comment by zijistark** [comment]
@escalonn Actually, we have title flags now (2.3), so it should be possible.  It's mostly just a matter of a whole lot of work to get "nice-looking" random perturbation with positive properties for play within pure Paradox Script (i.e., not using a landed_titles-aware script to pre-generate code to randomize de jure kingdom borders in a more heuristically sane way) vs. not much relative value-add as a customization decision.

In fact, not one of the modding improvements for 2.4 so far has addressed any algorithmic/computational expressiveness (i.e., the realm of the possible) hurdles for scripting, let alone any one-off scripting improvements like new conditions or commands.  However, Gars is still on the job, and hopefully he will implement several such deal-breakers, as altogether (between his work and stuff the CK2 team did), 2.3 was a big improvement.

**Comment by escalonn** [comment]
_looks at this issue again_
