### ISSUE TITLE
Assorted Vanilla Tweaks

### ISSUE THREAD

**Issue by thefinestsieve** [EMFTeam/EMF#79]
Mostly small things which should probably be adjusted:
* ~~Somewhat reduce chance of title and marriage begging~~ (implemented)
    * ~~Block characters from taking title ambition (required prerequisite for title begging) if they're monks or nuns or celibate~~ (implemented in PB)
* ~~Slightly reduce the chance of characters requesting to go into holy orders, and more significantly reduce chances when character is married~~ (implemented)
    * ~~Related: Centralize the holy order request events into one `hide_window = yes` handler event for efficiency and ease of adjustment (should keep modification of vanilla files to a minimum and make future updates easier)~~ (implemented)
* ~~Synchronize councilor ambition requirements with `job_titles.txt` requirements~~ (implemented in PB)

Feel free to toss more into the pile.

**Comment by thefinestsieve** [comment]
* Convert remaining councilor notification events to actual notification events when feasible to do so

**Comment by zijistark** [comment]
To that I would add: probably keep the councillor notification events (for councillors) as actual pop-ups if your liege is also a player.

**Comment by thefinestsieve** [comment]
My issue with that is, with the obvious exception of those which tell you that you've been injured or something akin, they don't give you any useful information. I don't need to know that I raised more levies for my liege. If I cared for some tactical reason I could just click on the province and check. Otherwise they're just noise. The only reason I don't suggest removing them altogether is because player preference varies and there's probably someone out there who would care.

**Comment by zijistark** [comment]
I think the 'ample levy reinforcements' thing is probably the only exception to what I said.  If I'm a chancellor and my liege is fabricating a claim in XYZ, then I want to see that I have successfully fabricated a claim on XYZ for him. If he's a player.
